import { type NextPage } from "next";
import Head from "next/head";
import Header from "~/components/Header";
import Post from "~/components/Post";
import { PlusIcon } from "@heroicons/react/24/outline";
import { api } from "~/utils/api";
import PickedArticle from "~/components/PickedArticle";
import LoadingPost from "~/components/LoadingPost";
import {useEffect} from 'react'
const Home: NextPage = () => {
  const posts = api.post.getPosts.useQuery()
  useEffect(() => {
    console.log('cookie:', document.cookie)
  }, [])
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col  bg-gradient-to-b from-[#111827] to-[#15162c]">
        <Header/>
        <div className="flex h-full flex-grow ">
          <div className=" border-white/40 border-r flex p-10 pl-40 pr-16 pt-5 flex-col">
            <div className="flex mb-10 sticky top-0 pt-4 z-10 bg-[#111827] text-white items-center justify-start space-x-10 border-b border-red-50 pb-5">
              <PlusIcon className="w-5 h-5 text-red-50"/>
              <p>For you</p>
              <p>Following</p>
            </div>
            <div className="flex flex-col">
              {posts.data ? posts.data.map((post) => {
                return <Post id={post.id} key={post.id} content={post.content} title={post.title} createdAt={post.updatedAt} creator={post.user.fullName} tag={post.tags[0]}/>
              }) : <><LoadingPost/><LoadingPost/><LoadingPost/></>}
            </div>
          </div>
          <div className="w-[50%]  p-10 hidden md:flex flex-col">
            <h2 className="text-white text-lg font-semibold">Monthly Best Articles</h2>
            <div className="flex flex-col">
              <PickedArticle/>
              <PickedArticle/>
              <PickedArticle/>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
