import type { NextPage } from "next";
import { useRouter } from "next/router";
import { useEffect } from "react";
import {PulseLoader} from "react-spinners"
import Head from "next/head";

import { api } from "~/utils/api";

const VerifyAccount: NextPage = () => {
    const router = useRouter();
    const verifyUser = api.user.verifyAccount.useMutation()
    useEffect(() => {
        const {id,verificationId} = router.query as {id:string, verificationId:string}
        if(id && verificationId){
            verifyUser.mutate({id,verificationId})
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [router])
    return (<>
        <Head>
          <title>Verify Account</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#111827] to-[#15162c]">
          {verifyUser.isLoading && <h1 className="text-2xl text-green-400 font-extrabold ">Verifying...</h1>}
          {verifyUser.error && <h1 className="text-2xl text-red-500 font-extrabold ">There was an error. Please try again later.</h1>}
          {verifyUser.isSuccess && <PulseLoader color="#3b82f6"/>}
        </main>
      </>
    );
}


export default VerifyAccount;