import { EnvelopeIcon } from "@heroicons/react/24/outline";
import Head from "next/head";
import Header from "~/components/Header";
import LoadingPost from "~/components/LoadingPost";
import { api } from "~/utils/api";
import type { GetServerSidePropsContext } from "next";
import Post from "~/components/Post";

export const getServerSideProps = (context: GetServerSidePropsContext) => {
  const { id } = context.query;

  return {
    props: {
      id,
    },
  };
};

const User = ({ id }: { id: string }) => {
  // this query returns all post from the user with the given id.
  // so getting just the creator name from one post we
  // can get the users name without making an extra request on the
  // backend server
  const posts = api.post.getUserPosts.useQuery(
    { userId: id },
    { staleTime: Infinity, refetchOnMount: "always", cacheTime: 0 }
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col  bg-gradient-to-b from-[#111827] to-[#15162c]">
        <Header />
        <div className="flex">
          <div className="flex w-full flex-col  border-r border-red-50/10 p-20 lg:w-[60%] ">
            <div className="flex items-center justify-between">
              <h1 className="text-4xl font-bold text-blue-500">
                {posts.data ? (
                  posts.data[0]?.user.fullName
                ) : (
                  <div className="h-5 w-[300px] animate-pulse rounded-lg bg-gray-500/60" />
                )}
              </h1>
              <div className="flex space-x-5 md:hidden">
                <button className="cursor-pointer rounded-lg bg-blue-500 px-4 py-1 text-white hover:shadow-xl">
                  Follow
                </button>
                <EnvelopeIcon className="h-10 w-10 cursor-pointer rounded-full bg-blue-500 p-2 text-white hover:shadow-xl" />
              </div>
            </div>
            <div className="my-5 mt-10 flex space-x-5 border-b border-red-50/10 pb-3  text-white">
              <p className="cursor-pointer transition-all ease-in hover:scale-105">
                Home
              </p>
              <p className="cursor-pointer transition-all ease-in hover:scale-105">
                About
              </p>
            </div>
            {posts.isLoading && (
              <>
                <LoadingPost />
                <LoadingPost />
                <LoadingPost />
              </>
            )}
            {posts.data &&
              posts.data.map((post) => {
                return (
                  <Post
                    key={post.id}
                    id={post.id}
                    creator={post.user.fullName}
                    createdAt={post.updatedAt}
                    content={post.content}
                    title={post.title}
                    tag={post?.tags[0]}
                    creatorId={id}
                  />
                );
              })}
          </div>
          <div className="sticky top-0 hidden h-fit max-w-[40%] flex-col  p-20 md:flex">
            <div className="h-20 w-20 rounded-full bg-blue-500" />

            <p className="ml-1 mt-5 text-lg font-bold text-white">
              {posts.data ? posts.data[0]?.user.fullName : ""}
            </p>
            <p className="ml-1 text-base text-red-50">270 Followers</p>
            <p className="ml-1 mt-3 text-sm text-red-50">
              NorCal writer. Tin House and VONA alum. Published in WaPo, The
              Audacity, Witness. Memoir-in-progress reckoning with migration and
              myth. www.jensoong.com
            </p>
            <div className="mt-8 flex items-center space-x-4">
              <button className="cursor-pointer rounded-lg bg-blue-500 px-5 py-2 text-white hover:shadow-xl">
                Follow
              </button>
              <EnvelopeIcon className="h-10 w-10 cursor-pointer rounded-full bg-blue-500 p-2 text-white hover:shadow-xl" />
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default User;
